const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
const GET_QUESTIONS = 'GET_QUESTIONS';
const GET_MORE_QUESTIONS = 'GET_MORE_QUESTIONS';

export default {
  REQUEST_QUESTIONS,
  GET_QUESTIONS,
  GET_MORE_QUESTIONS
};
